version: '3.8'

services:
  web:
    build: .
    container_name: m347-kn04a-web-test
    ports:
      - "8081:80"
    networks:
      kn04-network-test:


networks:
  kn04-network-test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254
