apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_PASSWORD: "password"
  ACCOUNT_DB_CONNECTION: "Server=db.default.svc.cluster.local;Port=3306;Database=m347kn08;User=root;Password=password;"
